@startuml
class alimento
class cliente 
class dia 
class encuesta 
class ingesta
class ingestaTipo
class list 
class main 
class menuInteractivo
class node 
class tree 

class cliente{
    -cliente:String
    -encuesta: Encuesta
    +cliente(String)
    +getnombre()
}
class alimento{
    -nombre:String
    +alimentos(String)
    +getnombre()
    }
class dia{
    -diaIndex:int
    -ingestasTree:Tree<IngestaTipo>
    +Dias(int)
    

}

@enduml
