public class Informacion {

    public static ValoresNutricionales getDatos(String nombre) {
        GenericList<String> productos = new GenericList<>();
        GenericList<ValoresNutricionales> datos = new GenericList<>();


        productos.insertEnd("Col");
        datos.insertEnd(new ValoresNutricionales(28, 65, 145, 312, "Verdura"));
        productos.insertEnd("Col de Bruselas");
        datos.insertEnd(new ValoresNutricionales(54, 492, 488, 114, "Verdura"));
        productos.insertEnd("Coliflor");
        datos.insertEnd(new ValoresNutricionales(30, 433, 429, 106, "Verdura"));
        productos.insertEnd("Endibia");
        datos.insertEnd(new ValoresNutricionales(22, 418, 313, 269, "Verdura"));
        productos.insertEnd("Escarola");
        datos.insertEnd(new ValoresNutricionales(37, 308, 445, 52, "Verdura"));
        productos.insertEnd("Espárragos");
        datos.insertEnd(new ValoresNutricionales(26, 114, 282, 99, "Verdura"));
        productos.insertEnd("Espárragos en lata");
        datos.insertEnd(new ValoresNutricionales(24, 383, 269, 218, "Verdura"));
        productos.insertEnd("Espinaca");
        datos.insertEnd(new ValoresNutricionales(32, 153, 456, 70, "Verdura"));
        productos.insertEnd("Espinacas congeladas");
        datos.insertEnd(new ValoresNutricionales(25, 49, 143, 348, "Verdura"));
        productos.insertEnd("Habas tiernas");
        datos.insertEnd(new ValoresNutricionales(64, 397, 128, 378, "Verdura"));
        productos.insertEnd("Hinojo");
        datos.insertEnd(new ValoresNutricionales(16, 182, 227, 12, "Verdura"));
        productos.insertEnd("Lechuga");
        datos.insertEnd(new ValoresNutricionales(18, 289, 215, 293, "Verdura"));
        productos.insertEnd("Nabos");
        datos.insertEnd(new ValoresNutricionales(29, 194, 144, 320, "Verdura"));
        productos.insertEnd("Papas cocidas");
        datos.insertEnd(new ValoresNutricionales(86, 38, 124, 184, "Verdura"));
        productos.insertEnd("Pepino");
        datos.insertEnd(new ValoresNutricionales(12, 54, 390, 317, "Verdura"));
        productos.insertEnd("Perejil");
        datos.insertEnd(new ValoresNutricionales(55, 90, 111, 148, "Verdura"));
        productos.insertEnd("Pimiento");
        datos.insertEnd(new ValoresNutricionales(22, 145, 119, 152, "Verdura"));
        productos.insertEnd("Porotos verdes");
        datos.insertEnd(new ValoresNutricionales(21, 83, 296, 358, "Verdura"));
        productos.insertEnd("Puerros");
        datos.insertEnd(new ValoresNutricionales(42, 432, 228, 398, "Verdura"));
        productos.insertEnd("Rábanos");
        datos.insertEnd(new ValoresNutricionales(20, 283, 220, 218, "Verdura"));
        productos.insertEnd("Remolacha");
        datos.insertEnd(new ValoresNutricionales(40, 181, 486, 129, "Verdura"));
        productos.insertEnd("Repollo");
        datos.insertEnd(new ValoresNutricionales(19, 306, 322, 230, "Verdura"));
        productos.insertEnd("Rúcula");
        datos.insertEnd(new ValoresNutricionales(37, 260, 494, 487, "Verdura"));
        productos.insertEnd("Soja, Brotes de");
        datos.insertEnd(new ValoresNutricionales(50, 388, 473, 39, "Verdura"));
        productos.insertEnd("Tomate triturado en conserva");
        datos.insertEnd(new ValoresNutricionales(39, 389, 292, 79, "Verdura"));
        productos.insertEnd("Tomates");
        datos.insertEnd(new ValoresNutricionales(22, 186, 451, 57, "Verdura"));
        productos.insertEnd("Trufa");
        datos.insertEnd(new ValoresNutricionales(92, 101, 273, 212, "Verdura"));
        productos.insertEnd("Zanahoria");
        datos.insertEnd(new ValoresNutricionales(42, 348, 402, 104, "Verdura"));
        productos.insertEnd("Zumo de tomate");
        datos.insertEnd(new ValoresNutricionales(21, 218, 203, 157, "Verdura"));
        productos.insertEnd("Arándanos");
        datos.insertEnd(new ValoresNutricionales(41, 70, 416, 458, "Fruta"));
        productos.insertEnd("Caqui");
        datos.insertEnd(new ValoresNutricionales(64, 179, 211, 324, "Fruta"));
        productos.insertEnd("Cereza");
        datos.insertEnd(new ValoresNutricionales(47, 303, 74, 184, "Fruta"));
        productos.insertEnd("Chirimoya");
        datos.insertEnd(new ValoresNutricionales(78, 116, 356, 69, "Fruta"));
        productos.insertEnd("Ciruela");
        datos.insertEnd(new ValoresNutricionales(44, 255, 31, 280, "Fruta"));
        productos.insertEnd("Ciruela seca");
        datos.insertEnd(new ValoresNutricionales(290, 435, 453, 432, "Fruta"));
        productos.insertEnd("Coco");
        datos.insertEnd(new ValoresNutricionales(646, 114, 351, 248, "Fruta"));
        productos.insertEnd("Dátil");
        datos.insertEnd(new ValoresNutricionales(279, 34, 122, 290, "Fruta"));
        productos.insertEnd("Dátil seco");
        datos.insertEnd(new ValoresNutricionales(306, 215, 485, 457, "Fruta"));
        productos.insertEnd("Frambuesa");
        datos.insertEnd(new ValoresNutricionales(40, 182, 287, 427, "Fruta"));
        productos.insertEnd("Fresas");
        datos.insertEnd(new ValoresNutricionales(36, 218, 186, 259, "Fruta"));
        productos.insertEnd("Granada");
        datos.insertEnd(new ValoresNutricionales(65, 397, 35, 140, "Fruta"));
        productos.insertEnd("Grosella");
        datos.insertEnd(new ValoresNutricionales(37, 41, 13, 71, "Fruta"));
        productos.insertEnd("Higos");
        datos.insertEnd(new ValoresNutricionales(80, 80, 15, 186, "Fruta"));
        productos.insertEnd("Higos secos");
        datos.insertEnd(new ValoresNutricionales(275, 147, 182, 442, "Fruta"));
        productos.insertEnd("Kiwi");
        datos.insertEnd(new ValoresNutricionales(51, 348, 303, 152, "Fruta"));
        productos.insertEnd("Limón");
        datos.insertEnd(new ValoresNutricionales(39, 366, 98, 289, "Fruta"));
        productos.insertEnd("Mandarina");
        datos.insertEnd(new ValoresNutricionales(40, 48, 134, 170, "Fruta"));
        productos.insertEnd("Mango");
        datos.insertEnd(new ValoresNutricionales(57, 309, 202, 208, "Fruta"));
        productos.insertEnd("Manzana");
        datos.insertEnd(new ValoresNutricionales(52, 112, 491, 161, "Fruta"));
        productos.insertEnd("Melón");
        datos.insertEnd(new ValoresNutricionales(31, 165, 372, 352, "Fruta"));
        productos.insertEnd("Mora");
        datos.insertEnd(new ValoresNutricionales(37, 443, 124, 71, "Fruta"));
        productos.insertEnd("Naranja");
        datos.insertEnd(new ValoresNutricionales(44, 335, 447, 13, "Fruta"));
        productos.insertEnd("Nectarina");
        datos.insertEnd(new ValoresNutricionales(64, 219, 413, 475, "Fruta"));
        productos.insertEnd("Nísperos");
        datos.insertEnd(new ValoresNutricionales(97, 206, 123, 133, "Fruta"));
        productos.insertEnd("Papaya");
        datos.insertEnd(new ValoresNutricionales(45, 211, 254, 212, "Fruta"));
        productos.insertEnd("Pera");
        datos.insertEnd(new ValoresNutricionales(61, 27, 412, 54, "Fruta"));
        productos.insertEnd("Piña");
        datos.insertEnd(new ValoresNutricionales(51, 137, 135, 494, "Fruta"));
        productos.insertEnd("Piña en almíbar");
        datos.insertEnd(new ValoresNutricionales(84, 479, 281, 241, "Fruta"));
        productos.insertEnd("Plátano");
        datos.insertEnd(new ValoresNutricionales(90, 433, 157, 330, "Fruta"));
        productos.insertEnd("Pomelo");
        datos.insertEnd(new ValoresNutricionales(30, 331, 428, 107, "Fruta"));
        productos.insertEnd("Sandía");
        datos.insertEnd(new ValoresNutricionales(30, 406, 108, 358, "Fruta"));
        productos.insertEnd("Uva");
        datos.insertEnd(new ValoresNutricionales(81, 431, 65, 412, "Fruta"));
        productos.insertEnd("Uva pasa");
        datos.insertEnd(new ValoresNutricionales(324, 87, 176, 416, "Fruta"));
        productos.insertEnd("Zumo de fruta");
        datos.insertEnd(new ValoresNutricionales(45, 167, 89, 205, "Fruta"));
        productos.insertEnd("Zumo de Naranja");
        datos.insertEnd(new ValoresNutricionales(42, 112, 351, 328, "Fruta"));
        productos.insertEnd("Almendras");
        datos.insertEnd(new ValoresNutricionales(620, 414, 486, 387, "Frutos secos"));
        productos.insertEnd("Avellanas");
        datos.insertEnd(new ValoresNutricionales(675, 25, 133, 284, "Frutos secos"));
        productos.insertEnd("Castañas");
        datos.insertEnd(new ValoresNutricionales(199, 91, 474, 374, "Frutos secos"));
        productos.insertEnd("Maní");
        datos.insertEnd(new ValoresNutricionales(560, 356, 249, 61, "Frutos secos"));
        productos.insertEnd("Nueces");
        datos.insertEnd(new ValoresNutricionales(660, 79, 317, 376, "Frutos secos"));
        productos.insertEnd("Piñones");
        datos.insertEnd(new ValoresNutricionales(660, 62, 247, 89, "Frutos secos"));
        productos.insertEnd("Pistacho");
        datos.insertEnd(new ValoresNutricionales(581, 55, 22, 468, "Frutos secos"));
        productos.insertEnd("Cuajada");
        datos.insertEnd(new ValoresNutricionales(92, 301, 270, 324, "Lacteo"));
        productos.insertEnd("Flan de huevo");
        datos.insertEnd(new ValoresNutricionales(126, 258, 67, 295, "Lacteo"));
        productos.insertEnd("Flan de vainilla");
        datos.insertEnd(new ValoresNutricionales(102, 317, 116, 250, "Lacteo"));
        productos.insertEnd("Helados lácteos");
        datos.insertEnd(new ValoresNutricionales(167, 152, 413, 306, "Lacteo"));
        productos.insertEnd("Leche condensada c/azúcar");
        datos.insertEnd(new ValoresNutricionales(350, 369, 23, 141, "Lacteo"));
        productos.insertEnd("Leche condensada s/azúcar");
        datos.insertEnd(new ValoresNutricionales(160, 204, 485, 238, "Lacteo"));
        productos.insertEnd("Leche de cabra");
        datos.insertEnd(new ValoresNutricionales(72, 417, 448, 477, "Lacteo"));
        productos.insertEnd("Leche de oveja");
        datos.insertEnd(new ValoresNutricionales(96, 450, 248, 364, "Lacteo"));
        productos.insertEnd("Leche descremada");
        datos.insertEnd(new ValoresNutricionales(36, 464, 59, 220, "Lacteo"));
        productos.insertEnd("Leche en polvo descremada");
        datos.insertEnd(new ValoresNutricionales(373, 389, 267, 282, "Lacteo"));
        productos.insertEnd("Leche en polvo entera");
        datos.insertEnd(new ValoresNutricionales(500, 101, 151, 399, "Lacteo"));
        productos.insertEnd("Leche entera");
        datos.insertEnd(new ValoresNutricionales(68, 378, 132, 319, "Lacteo"));
        productos.insertEnd("Leche semi descremada");
        datos.insertEnd(new ValoresNutricionales(49, 224, 428, 3, "Lacteo"));
        productos.insertEnd("Mousse");
        datos.insertEnd(new ValoresNutricionales(177, 131, 16, 400, "Lacteo"));
        productos.insertEnd("Nata o crema de leche");
        datos.insertEnd(new ValoresNutricionales(298, 349, 497, 160, "Lacteo"));
        productos.insertEnd("Queso blanco desnatado");
        datos.insertEnd(new ValoresNutricionales(70, 392, 55, 328, "Lacteo"));
        productos.insertEnd("Queso Brie");
        datos.insertEnd(new ValoresNutricionales(263, 39, 456, 436, "Lacteo"));
        productos.insertEnd("Queso cammembert");
        datos.insertEnd(new ValoresNutricionales(312, 28, 239, 396, "Lacteo"));
        productos.insertEnd("Queso cheddar");
        datos.insertEnd(new ValoresNutricionales(381, 100, 112, 368, "Lacteo"));
        productos.insertEnd("Queso crema");
        datos.insertEnd(new ValoresNutricionales(245, 150, 78, 435, "Lacteo"));
        productos.insertEnd("Queso de bola");
        datos.insertEnd(new ValoresNutricionales(349, 147, 178, 124, "Lacteo"));
        productos.insertEnd("Queso de Burgos");
        datos.insertEnd(new ValoresNutricionales(174, 35, 182, 87, "Lacteo"));
        productos.insertEnd("Queso de oveja");
        datos.insertEnd(new ValoresNutricionales(245, 139, 158, 447, "Lacteo"));
        productos.insertEnd("Queso edam");
        datos.insertEnd(new ValoresNutricionales(306, 292, 438, 193, "Lacteo"));
        productos.insertEnd("Queso emmental");
        datos.insertEnd(new ValoresNutricionales(415, 236, 8, 61, "Lacteo"));
        productos.insertEnd("Queso fundido untable");
        datos.insertEnd(new ValoresNutricionales(285, 83, 409, 244, "Lacteo"));
        productos.insertEnd("Queso gruyere");
        datos.insertEnd(new ValoresNutricionales(391, 161, 401, 23, "Lacteo"));
        productos.insertEnd("Queso manchego");
        datos.insertEnd(new ValoresNutricionales(376, 134, 156, 51, "Lacteo"));
        productos.insertEnd("Queso mozzarella");
        datos.insertEnd(new ValoresNutricionales(245, 100, 430, 297, "Lacteo"));
        productos.insertEnd("Queso parmesano");
        datos.insertEnd(new ValoresNutricionales(393, 145, 390, 42, "Lacteo"));
        productos.insertEnd("Queso ricota");
        datos.insertEnd(new ValoresNutricionales(400, 2, 53, 54, "Lacteo"));
        productos.insertEnd("Queso roquefort");
        datos.insertEnd(new ValoresNutricionales(405, 218, 171, 39, "Lacteo"));
        productos.insertEnd("Requesón");
        datos.insertEnd(new ValoresNutricionales(96, 256, 142, 169, "Lacteo"));
        productos.insertEnd("Yogur desnatado");
        datos.insertEnd(new ValoresNutricionales(45, 206, 442, 172, "Lacteo"));
        productos.insertEnd("Yogur desnatado con frutas");
        datos.insertEnd(new ValoresNutricionales(82, 168, 381, 344, "Lacteo"));
        productos.insertEnd("Yogur enriquecido con nata");
        datos.insertEnd(new ValoresNutricionales(65, 328, 493, 484, "Lacteo"));
        productos.insertEnd("Yogur natural");
        datos.insertEnd(new ValoresNutricionales(62, 276, 165, 38, "Lacteo"));
        productos.insertEnd("Yogur natural con fruta");
        datos.insertEnd(new ValoresNutricionales(100, 438, 3, 37, "Lacteo"));
        productos.insertEnd("Bacon");
        datos.insertEnd(new ValoresNutricionales(665, 261, 46, 494, "Carne"));
        productos.insertEnd("Butifarra cocida");
        datos.insertEnd(new ValoresNutricionales(390, 72, 32, 104, "Carne"));
        productos.insertEnd("Butifarra, salchicha fresca");
        datos.insertEnd(new ValoresNutricionales(326, 288, 190, 20, "Carne"));
        productos.insertEnd("Cabrito");
        datos.insertEnd(new ValoresNutricionales(127, 139, 383, 6, "Carne"));
        productos.insertEnd("Cerdo, chuleta");
        datos.insertEnd(new ValoresNutricionales(330, 382, 344, 256, "Carne"));
        productos.insertEnd("Cerdo, hígado");
        datos.insertEnd(new ValoresNutricionales(153, 83, 49, 145, "Carne"));
        productos.insertEnd("Cerdo, lomo");
        datos.insertEnd(new ValoresNutricionales(208, 380, 117, 343, "Carne"));
        productos.insertEnd("Chicharrón");
        datos.insertEnd(new ValoresNutricionales(601, 305, 473, 313, "Carne"));
        productos.insertEnd("Chorizo");
        datos.insertEnd(new ValoresNutricionales(468, 455, 97, 174, "Carne"));
        productos.insertEnd("Ciervo");
        datos.insertEnd(new ValoresNutricionales(120, 285, 242, 415, "Carne"));
        productos.insertEnd("Codorniz y perdiz");
        datos.insertEnd(new ValoresNutricionales(114, 186, 250, 259, "Carne"));
        productos.insertEnd("Conejo, liebre");
        datos.insertEnd(new ValoresNutricionales(162, 1, 234, 267, "Carne"));
        productos.insertEnd("Cordero lechón");
        datos.insertEnd(new ValoresNutricionales(105, 316, 482, 128, "Carne"));
        productos.insertEnd("Cordero pierna");
        datos.insertEnd(new ValoresNutricionales(98, 122, 166, 1, "Carne"));
        productos.insertEnd("Cordero, costillas");
        datos.insertEnd(new ValoresNutricionales(215, 469, 157, 70, "Carne"));
        productos.insertEnd("Cordero, hígado");
        datos.insertEnd(new ValoresNutricionales(132, 369, 467, 451, "Carne"));
        productos.insertEnd("Faisán");
        datos.insertEnd(new ValoresNutricionales(144, 379, 247, 35, "Carne"));
        productos.insertEnd("Foie-Gras");
        datos.insertEnd(new ValoresNutricionales(518, 468, 14, 316, "Carne"));
        productos.insertEnd("Gallina");
        datos.insertEnd(new ValoresNutricionales(369, 174, 394, 303, "Carne"));
        productos.insertEnd("Hamburguesa");
        datos.insertEnd(new ValoresNutricionales(230, 244, 297, 56, "Carne"));
        productos.insertEnd("Jabalí");
        datos.insertEnd(new ValoresNutricionales(107, 373, 395, 46, "Carne"));
        productos.insertEnd("Jamón");
        datos.insertEnd(new ValoresNutricionales(380, 488, 456, 303, "Carne"));
        productos.insertEnd("Jamón cocido");
        datos.insertEnd(new ValoresNutricionales(126, 419, 61, 184, "Carne"));
        productos.insertEnd("Jamón crudo");
        datos.insertEnd(new ValoresNutricionales(296, 47, 459, 220, "Carne"));
        productos.insertEnd("Jamón York");
        datos.insertEnd(new ValoresNutricionales(289, 23, 392, 77, "Carne"));
        productos.insertEnd("Lengua de vaca");
        datos.insertEnd(new ValoresNutricionales(191, 83, 3, 279, "Carne"));
        productos.insertEnd("Lomo embuchado");
        datos.insertEnd(new ValoresNutricionales(380, 421, 407, 70, "Carne"));
        productos.insertEnd("Mortadela");
        datos.insertEnd(new ValoresNutricionales(265, 311, 39, 462, "Carne"));
        productos.insertEnd("Pato");
        datos.insertEnd(new ValoresNutricionales(200, 448, 1, 408, "Carne"));
        productos.insertEnd("Pavo, Muslo");
        datos.insertEnd(new ValoresNutricionales(186, 19, 198, 12, "Carne"));
        productos.insertEnd("Pavo, Pechuga");
        datos.insertEnd(new ValoresNutricionales(134, 302, 431, 391, "Carne"));
        productos.insertEnd("Perdiz");
        datos.insertEnd(new ValoresNutricionales(120, 74, 65, 110, "Carne"));
        productos.insertEnd("Pies de cerdo");
        datos.insertEnd(new ValoresNutricionales(290, 256, 498, 66, "Carne"));
        productos.insertEnd("Pollo, Hígado");
        datos.insertEnd(new ValoresNutricionales(129, 80, 420, 23, "Carne"));
        productos.insertEnd("Pollo, Muslo");
        datos.insertEnd(new ValoresNutricionales(186, 428, 145, 364, "Carne"));
        productos.insertEnd("Pollo");
        datos.insertEnd(new ValoresNutricionales(134, 289, 32, 373, "Carne"));
        productos.insertEnd("Salami");
        datos.insertEnd(new ValoresNutricionales(325, 120, 478, 448, "Carne"));
        productos.insertEnd("Salchicha Frankfurt");
        datos.insertEnd(new ValoresNutricionales(315, 295, 42, 113, "Carne"));
        productos.insertEnd("Salchichón");
        datos.insertEnd(new ValoresNutricionales(294, 66, 342, 7, "Carne"));
        productos.insertEnd("Ternera");
        datos.insertEnd(new ValoresNutricionales(181, 54, 213, 489, "Carne"));
        productos.insertEnd("Ternera, chuleta");
        datos.insertEnd(new ValoresNutricionales(168, 295, 239, 410, "Carne"));
        productos.insertEnd("Ternera, hígado");
        datos.insertEnd(new ValoresNutricionales(140, 143, 398, 126, "Carne"));
        productos.insertEnd("Ternera, lengua");
        datos.insertEnd(new ValoresNutricionales(207, 458, 423, 315, "Carne"));
        productos.insertEnd("Ternera, riñón");
        datos.insertEnd(new ValoresNutricionales(86, 270, 74, 162, "Carne"));
        productos.insertEnd("Ternera, sesos");
        datos.insertEnd(new ValoresNutricionales(125, 239, 452, 25, "Carne"));
        productos.insertEnd("Ternera, solomillo");
        datos.insertEnd(new ValoresNutricionales(290, 245, 499, 95, "Carne"));
        productos.insertEnd("Tira de asado");
        datos.insertEnd(new ValoresNutricionales(401, 409, 272, 332, "Carne"));
        productos.insertEnd("Tripas");
        datos.insertEnd(new ValoresNutricionales(100, 129, 490, 41, "Carne"));
        productos.insertEnd("Vacuno, Hígado");
        datos.insertEnd(new ValoresNutricionales(129, 150, 220, 235, "Carne"));
        productos.insertEnd("Almejas");
        datos.insertEnd(new ValoresNutricionales(50, 214, 459, 386, "Pescado"));
        productos.insertEnd("Anchoas");
        datos.insertEnd(new ValoresNutricionales(175, 152, 331, 439, "Pescado"));
        productos.insertEnd("Anguilas");
        datos.insertEnd(new ValoresNutricionales(200, 172, 274, 95, "Pescado"));
        productos.insertEnd("Atún en lata con aceite vegetal");
        datos.insertEnd(new ValoresNutricionales(280, 451, 125, 323, "Pescado"));
        productos.insertEnd("Atún en lata con agua");
        datos.insertEnd(new ValoresNutricionales(127, 342, 76, 347, "Pescado"));
        productos.insertEnd("Atún fresco");
        datos.insertEnd(new ValoresNutricionales(225, 384, 155, 248, "Pescado"));
        productos.insertEnd("Bacalao fresco");
        datos.insertEnd(new ValoresNutricionales(74, 104, 258, 334, "Pescado"));
        productos.insertEnd("Bacalao seco");
        datos.insertEnd(new ValoresNutricionales(322, 129, 174, 284, "Pescado"));
        productos.insertEnd("Besugo");
        datos.insertEnd(new ValoresNutricionales(118, 237, 37, 313, "Pescado"));
        productos.insertEnd("Caballa");
        datos.insertEnd(new ValoresNutricionales(153, 327, 446, 213, "Pescado"));
        productos.insertEnd("Calamar");
        datos.insertEnd(new ValoresNutricionales(82, 253, 11, 362, "Pescado"));
        productos.insertEnd("Cangrejo");
        datos.insertEnd(new ValoresNutricionales(85, 244, 119, 319, "Pescado"));
        productos.insertEnd("Caviar");
        datos.insertEnd(new ValoresNutricionales(233, 294, 54, 297, "Pescado"));
        productos.insertEnd("Congrio");
        datos.insertEnd(new ValoresNutricionales(112, 278, 403, 170, "Pescado"));
        productos.insertEnd("Dorada");
        datos.insertEnd(new ValoresNutricionales(80, 82, 404, 82, "Pescado"));
        productos.insertEnd("Gallo");
        datos.insertEnd(new ValoresNutricionales(73, 69, 231, 241, "Pescado"));
        productos.insertEnd("Gambas");
        datos.insertEnd(new ValoresNutricionales(96, 491, 380, 409, "Pescado"));
        productos.insertEnd("Langosta");
        datos.insertEnd(new ValoresNutricionales(67, 152, 231, 76, "Pescado"));
        productos.insertEnd("Langostino");
        datos.insertEnd(new ValoresNutricionales(96, 168, 259, 478, "Pescado"));
        productos.insertEnd("Lenguado");
        datos.insertEnd(new ValoresNutricionales(73, 181, 189, 118, "Pescado"));
        productos.insertEnd("Lubina");
        datos.insertEnd(new ValoresNutricionales(118, 411, 43, 18, "Pescado"));
        productos.insertEnd("Lucio");
        datos.insertEnd(new ValoresNutricionales(81, 21, 340, 217, "Pescado"));
        productos.insertEnd("Mejillón");
        datos.insertEnd(new ValoresNutricionales(74, 139, 360, 22, "Pescado"));
        productos.insertEnd("Merluza");
        datos.insertEnd(new ValoresNutricionales(86, 392, 158, 16, "Pescado"));
        productos.insertEnd("Mero");
        datos.insertEnd(new ValoresNutricionales(118, 168, 148, 71, "Pescado"));
        productos.insertEnd("Ostras");
        datos.insertEnd(new ValoresNutricionales(80, 3, 58, 129, "Pescado"));
        productos.insertEnd("Pejerrey");
        datos.insertEnd(new ValoresNutricionales(87, 140, 465, 21, "Pescado"));
        productos.insertEnd("Pez espada");
        datos.insertEnd(new ValoresNutricionales(109, 305, 170, 5, "Pescado"));
        productos.insertEnd("Pulpo");
        datos.insertEnd(new ValoresNutricionales(57, 210, 95, 227, "Pescado"));
        productos.insertEnd("Rodaballo");
        datos.insertEnd(new ValoresNutricionales(81, 308, 248, 3, "Pescado"));
        productos.insertEnd("Salmón");
        datos.insertEnd(new ValoresNutricionales(172, 392, 345, 16, "Pescado"));
        productos.insertEnd("Salmón ahumado");
        datos.insertEnd(new ValoresNutricionales(154, 250, 136, 208, "Pescado"));
        productos.insertEnd("Salmonete");
        datos.insertEnd(new ValoresNutricionales(97, 156, 38, 87, "Pescado"));
        productos.insertEnd("Sardina en lata con aceite vegetal");
        datos.insertEnd(new ValoresNutricionales(192, 22, 372, 35, "Pescado"));
        productos.insertEnd("Sardinas");
        datos.insertEnd(new ValoresNutricionales(151, 26, 455, 76, "Pescado"));
        productos.insertEnd("Trucha");
        datos.insertEnd(new ValoresNutricionales(94, 241, 449, 118, "Pescado"));
        productos.insertEnd("Azúcar");
        datos.insertEnd(new ValoresNutricionales(380, 337, 399, 312, "Dulce"));
        productos.insertEnd("Cacao en polvo con azúcar instantáneo");
        datos.insertEnd(new ValoresNutricionales(366, 436, 34, 90, "Dulce"));
        productos.insertEnd("Caramelos");
        datos.insertEnd(new ValoresNutricionales(378, 359, 299, 71, "Dulce"));
        productos.insertEnd("Chocolate con leche");
        datos.insertEnd(new ValoresNutricionales(550, 135, 26, 177, "Dulce"));
        productos.insertEnd("Chocolate sin leche");
        datos.insertEnd(new ValoresNutricionales(530, 330, 72, 25, "Dulce"));
        productos.insertEnd("Crema chocolate con avellanas");
        datos.insertEnd(new ValoresNutricionales(549, 211, 243, 293, "Dulce"));
        productos.insertEnd("Dulce de membrillo");
        datos.insertEnd(new ValoresNutricionales(215, 364, 280, 97, "Dulce"));
        productos.insertEnd("Helados de agua");
        datos.insertEnd(new ValoresNutricionales(139, 300, 20, 242, "Dulce"));
        productos.insertEnd("Mermeladas con azúcar");
        datos.insertEnd(new ValoresNutricionales(280, 140, 451, 442, "Dulce"));
        productos.insertEnd("Mermeladas sin azúcar");
        datos.insertEnd(new ValoresNutricionales(145, 127, 250, 47, "Dulce"));
        productos.insertEnd("Miel");
        datos.insertEnd(new ValoresNutricionales(300, 247, 380, 413, "Dulce"));
        productos.insertEnd("Arroz blanco");
        datos.insertEnd(new ValoresNutricionales(354, 64, 429, 327, "Cereal"));
        productos.insertEnd("Arroz integral");
        datos.insertEnd(new ValoresNutricionales(350, 1, 328, 9, "Cereal"));
        productos.insertEnd("Avena");
        datos.insertEnd(new ValoresNutricionales(367, 20, 344, 46, "Cereal"));
        productos.insertEnd("Cebada");
        datos.insertEnd(new ValoresNutricionales(373, 40, 201, 223, "Cereal"));
        productos.insertEnd("Centeno");
        datos.insertEnd(new ValoresNutricionales(350, 4, 337, 269, "Cereal"));
        productos.insertEnd("Cereales con chocolate");
        datos.insertEnd(new ValoresNutricionales(358, 377, 227, 425, "Cereal"));
        productos.insertEnd("Cereales desayuno, con miel");
        datos.insertEnd(new ValoresNutricionales(386, 64, 255, 368, "Cereal"));
        productos.insertEnd("Copos de maíz");
        datos.insertEnd(new ValoresNutricionales(350, 66, 90, 270, "Cereal"));
        productos.insertEnd("Harina de maíz");
        datos.insertEnd(new ValoresNutricionales(349, 175, 297, 445, "Cereal"));
        productos.insertEnd("Harina de trigo integral");
        datos.insertEnd(new ValoresNutricionales(340, 95, 361, 346, "Cereal"));
        productos.insertEnd("Harina de trigo refinada");
        datos.insertEnd(new ValoresNutricionales(353, 412, 474, 469, "Cereal"));
        productos.insertEnd("Pan de centeno");
        datos.insertEnd(new ValoresNutricionales(241, 31, 197, 209, "Cereal"));
        productos.insertEnd("Pan de trigo blanco");
        datos.insertEnd(new ValoresNutricionales(255, 71, 406, 255, "Cereal"));
        productos.insertEnd("Pan de trigo integral");
        datos.insertEnd(new ValoresNutricionales(239, 215, 273, 489, "Cereal"));
        productos.insertEnd("Pan de trigo molde blanco");
        datos.insertEnd(new ValoresNutricionales(233, 246, 130, 228, "Cereal"));
        productos.insertEnd("Pan de trigo molde integral");
        datos.insertEnd(new ValoresNutricionales(216, 228, 61, 492, "Cereal"));
        productos.insertEnd("Pasta al huevo");
        datos.insertEnd(new ValoresNutricionales(368, 367, 399, 163, "Cereal"));
        productos.insertEnd("Pasta de sémola");
        datos.insertEnd(new ValoresNutricionales(361, 187, 260, 332, "Cereal"));
        productos.insertEnd("Polenta");
        datos.insertEnd(new ValoresNutricionales(358, 399, 333, 403, "Cereal"));
        productos.insertEnd("Sémola de trigo");
        datos.insertEnd(new ValoresNutricionales(368, 291, 477, 260, "Cereal"));
        productos.insertEnd("Yuca");
        datos.insertEnd(new ValoresNutricionales(338, 5, 222, 171, "Cereal"));
        productos.insertEnd("Garbanzos");
        datos.insertEnd(new ValoresNutricionales(361, 483, 65, 457, "Legumbre"));
        productos.insertEnd("Judías");
        datos.insertEnd(new ValoresNutricionales(343, 187, 417, 454, "Legumbre"));
        productos.insertEnd("Lentejas");
        datos.insertEnd(new ValoresNutricionales(336, 179, 419, 444, "Legumbre"));
        productos.insertEnd("Clara");
        datos.insertEnd(new ValoresNutricionales(48, 215, 134, 441, "Huevo"));
        productos.insertEnd("Huevo duro");
        datos.insertEnd(new ValoresNutricionales(147, 399, 233, 144, "Huevo"));
        productos.insertEnd("Huevo entero");
        datos.insertEnd(new ValoresNutricionales(162, 207, 187, 95, "Huevo"));
        productos.insertEnd("Yema");
        datos.insertEnd(new ValoresNutricionales(368, 140, 116, 466, "Huevo"));
        productos.insertEnd("Bizcocho");
        datos.insertEnd(new ValoresNutricionales(456, 152, 322, 426, "Dulce"));
        productos.insertEnd("Croissant chocolate");
        datos.insertEnd(new ValoresNutricionales(469, 27, 127, 303, "Dulce"));
        productos.insertEnd("Croissant, donut");
        datos.insertEnd(new ValoresNutricionales(456, 1, 166, 0, "Dulce"));
        productos.insertEnd("Galletas de chocolate");
        datos.insertEnd(new ValoresNutricionales(524, 374, 377, 408, "Dulce"));
        productos.insertEnd("Galletas de mantequilla tipo “Danesas”");
        datos.insertEnd(new ValoresNutricionales(397, 486, 241, 94, "Dulce"));
        productos.insertEnd("Galletas saladas");
        datos.insertEnd(new ValoresNutricionales(464, 268, 448, 162, "Dulce"));
        productos.insertEnd("Magdalenas");
        datos.insertEnd(new ValoresNutricionales(469, 220, 382, 364, "Dulce"));
        productos.insertEnd("Pasta de hojaldre cocida");
        datos.insertEnd(new ValoresNutricionales(565, 157, 157, 260, "Cereal"));
        productos.insertEnd("Pastel de manzana");
        datos.insertEnd(new ValoresNutricionales(311, 452, 59, 151, "Dulce"));
        productos.insertEnd("Pastel de manzana, masa hojaldre");
        datos.insertEnd(new ValoresNutricionales(456, 450, 228, 282, "Dulce"));
        productos.insertEnd("Pastel de queso");
        datos.insertEnd(new ValoresNutricionales(414, 115, 291, 336, "Dulce"));
        productos.insertEnd("Agua ardiente");
        datos.insertEnd(new ValoresNutricionales(280, 309, 303, 421, "Bebida"));
        productos.insertEnd("Agua tónica");
        datos.insertEnd(new ValoresNutricionales(34, 180, 317, 127, "Bebida"));
        productos.insertEnd("Anís");
        datos.insertEnd(new ValoresNutricionales(312, 287, 417, 210, "Bebida"));
        productos.insertEnd("Batido lácteo de cacao");
        datos.insertEnd(new ValoresNutricionales(100, 222, 383, 27, "Bebida"));
        productos.insertEnd("Cacao en polvo sin azúcar a la taza");
        datos.insertEnd(new ValoresNutricionales(439, 421, 67, 145, "Bebida"));
        productos.insertEnd("Café");
        datos.insertEnd(new ValoresNutricionales(1, 113, 123, 109, "Bebida"));
        productos.insertEnd("Cerveza negra");
        datos.insertEnd(new ValoresNutricionales(37, 397, 228, 177, "Bebida"));
        productos.insertEnd("Cerveza rubia");
        datos.insertEnd(new ValoresNutricionales(45, 466, 287, 159, "Bebida"));
        productos.insertEnd("Champaña demi-sec");
        datos.insertEnd(new ValoresNutricionales(90, 267, 29, 450, "Bebida"));
        productos.insertEnd("Champaña dulce");
        datos.insertEnd(new ValoresNutricionales(118, 303, 26, 304, "Bebida"));
        productos.insertEnd("Champaña seca");
        datos.insertEnd(new ValoresNutricionales(85, 288, 467, 199, "Bebida"));
        productos.insertEnd("Coñac, brandy");
        datos.insertEnd(new ValoresNutricionales(243, 435, 63, 50, "Bebida"));
        productos.insertEnd("Crema de cacao");
        datos.insertEnd(new ValoresNutricionales(260, 388, 368, 449, "Bebida"));
        productos.insertEnd("Daiquiri");
        datos.insertEnd(new ValoresNutricionales(122, 428, 480, 299, "Bebida"));
        productos.insertEnd("Gin & Tónica");
        datos.insertEnd(new ValoresNutricionales(76, 36, 84, 20, "Bebida"));
        productos.insertEnd("Ginebra");
        datos.insertEnd(new ValoresNutricionales(244, 444, 25, 455, "Bebida"));
        productos.insertEnd("Leche de almendras");
        datos.insertEnd(new ValoresNutricionales(335, 347, 259, 480, "Bebida"));
        productos.insertEnd("Licor de caña");
        datos.insertEnd(new ValoresNutricionales(273, 428, 371, 418, "Bebida"));
        productos.insertEnd("Piña colada");
        datos.insertEnd(new ValoresNutricionales(194, 392, 318, 188, "Bebida"));
        productos.insertEnd("Pisco");
        datos.insertEnd(new ValoresNutricionales(210, 11, 40, 450, "Bebida"));
        productos.insertEnd("Refrescos carbonatados");
        datos.insertEnd(new ValoresNutricionales(48, 325, 372, 118, "Bebida"));
        productos.insertEnd("Ron");
        datos.insertEnd(new ValoresNutricionales(244, 120, 406, 395, "Bebida"));
        productos.insertEnd("Sidra dulce");
        datos.insertEnd(new ValoresNutricionales(33, 390, 370, 97, "Bebida"));
        productos.insertEnd("Sidra seca");
        datos.insertEnd(new ValoresNutricionales(35, 260, 191, 432, "Bebida"));
        productos.insertEnd("Té");
        datos.insertEnd(new ValoresNutricionales(1, 191, 475, 40, "Bebida"));
        productos.insertEnd("Vermouth amargo");
        datos.insertEnd(new ValoresNutricionales(112, 350, 442, 203, "Bebida"));
        productos.insertEnd("Vermouth dulce");
        datos.insertEnd(new ValoresNutricionales(160, 297, 45, 437, "Bebida"));
        productos.insertEnd("Vino de mesa");
        datos.insertEnd(new ValoresNutricionales(70, 132, 269, 202, "Bebida"));
        productos.insertEnd("Vino dulce, jerez");
        datos.insertEnd(new ValoresNutricionales(160, 121, 401, 24, "Bebida"));
        productos.insertEnd("Vino oporto");
        datos.insertEnd(new ValoresNutricionales(160, 66, 274, 209, "Bebida"));
        productos.insertEnd("Vodka");
        datos.insertEnd(new ValoresNutricionales(315, 191, 96, 423, "Bebida"));
        productos.insertEnd("Whisky");
        datos.insertEnd(new ValoresNutricionales(244, 299, 4, 170, "Bebida"));
        productos.insertEnd("Aceite de girasol");
        datos.insertEnd(new ValoresNutricionales(900, 207, 401, 439, "Otros"));
        productos.insertEnd("Aceite de oliva");
        datos.insertEnd(new ValoresNutricionales(900, 471, 417, 56, "Otros"));
        productos.insertEnd("Manteca");
        datos.insertEnd(new ValoresNutricionales(670, 224, 201, 439, "Otros"));
        productos.insertEnd("Mantequilla");
        datos.insertEnd(new ValoresNutricionales(752, 7, 143, 259, "Otros"));
        productos.insertEnd("Margarina vegetal");
        datos.insertEnd(new ValoresNutricionales(752, 410, 458, 153, "Otros"));
        productos.insertEnd("Bechamel");
        datos.insertEnd(new ValoresNutricionales(115, 227, 118, 465, "Otros"));
        productos.insertEnd("Caldos concentrados");
        datos.insertEnd(new ValoresNutricionales(259, 454, 499, 289, "Otros"));
        productos.insertEnd("Ketchup");
        datos.insertEnd(new ValoresNutricionales(98, 198, 171, 117, "Otros"));
        productos.insertEnd("Mayonesa");
        datos.insertEnd(new ValoresNutricionales(718, 210, 146, 185, "Otros"));
        productos.insertEnd("Mayonesa light");
        datos.insertEnd(new ValoresNutricionales(374, 279, 484, 435, "Otros"));
        productos.insertEnd("Mostaza");
        datos.insertEnd(new ValoresNutricionales(15, 104, 465, 459, "Otros"));
        productos.insertEnd("Salsa de soja");
        datos.insertEnd(new ValoresNutricionales(61, 309, 291, 468, "Otros"));
        productos.insertEnd("Salsa de tomate en conserva");
        datos.insertEnd(new ValoresNutricionales(86, 117, 43, 154, "Otros"));
        productos.insertEnd("Sofrito");
        datos.insertEnd(new ValoresNutricionales(116, 337, 329, 382, "Otros"));
        productos.insertEnd("Vinagres");
        datos.insertEnd(new ValoresNutricionales(8, 0, 310, 426, "Otros"));

        int pos = productos.indexOf(nombre);
        if (pos >= 0) {
            return datos.getValorPorPosicion(pos);
        }
        return null;

    }
}
