@startuml

    title Diagrama de clases

    class Client

    class FoodData

    class Manager {
        - Tree<TreeObject> tree
    }

    package TreeObjects{
        class Intake
        class Food
        class Day
        class Survey

    }
    package utils {
        interface IDataStructure
        class List
        class ListNode
        class Shortcut
        class Tree
        class TreeNode
        interface TreeObject
    }



    Tree --|> IDataStructure
    List --|> IDataStructure

    TreeObjects --|> TreeObject

@enduml