package clases;

import Coleciones.GenericList;

public class InformacionNutricional {


    public static ValoresNutricionales getDatos(String nombre) {
        GenericList<String> productos = new GenericList<>(null);
        GenericList<ValoresNutricionales> datos = new GenericList<>(null);

        productos.insertEnd("Col"); datos.insertEnd(new ValoresNutricionales(25, 5, 1.5, 0.3, "Verdura"));
        productos.insertEnd("Col de Bruselas"); datos.insertEnd(new ValoresNutricionales(43, 5, 3.4, 0.9, "Verdura"));
        productos.insertEnd("Coliflor"); datos.insertEnd(new ValoresNutricionales(25, 2, 1.9, 0.3, "Verdura"));
        productos.insertEnd("Endibia"); datos.insertEnd(new ValoresNutricionales(17, 1, 1.3, 0.2, "Verdura"));
        productos.insertEnd("Escarola"); datos.insertEnd(new ValoresNutricionales(17, 1, 1.2, 0.2, "Verdura"));
        productos.insertEnd("Espárragos"); datos.insertEnd(new ValoresNutricionales(20, 1.8, 2.2, 0.2, "Verdura"));
        productos.insertEnd("Espárragos en lata"); datos.insertEnd(new ValoresNutricionales(16, 1.3, 1.7, 0.2, "Verdura"));
        productos.insertEnd("Espinaca"); datos.insertEnd(new ValoresNutricionales(23, 2.9, 2.9, 0.4, "Verdura"));
        productos.insertEnd("Espinacas congeladas"); datos.insertEnd(new ValoresNutricionales(23, 3.6, 2.9, 0.4, "Verdura"));
        productos.insertEnd("Habas tiernas"); datos.insertEnd(new ValoresNutricionales(88, 8, 5, 0.6, "Verdura"));
        productos.insertEnd("Hinojo"); datos.insertEnd(new ValoresNutricionales(20, 3.9, 1.5, 0.2, "Verdura"));
        productos.insertEnd("Lechuga"); datos.insertEnd(new ValoresNutricionales(5, 1, 1, 0.2, "Verdura"));
        productos.insertEnd("Nabos"); datos.insertEnd(new ValoresNutricionales(28, 2.8, 1.3, 0.2, "Verdura"));
        productos.insertEnd("Patatas cocidas"); datos.insertEnd(new ValoresNutricionales(87, 2, 2, 0.1, "Verdura"));
        productos.insertEnd("Pepino"); datos.insertEnd(new ValoresNutricionales(16, 1.7, 0.6, 0.2, "Verdura"));
        productos.insertEnd("Perejil"); datos.insertEnd(new ValoresNutricionales(36, 0.9, 3, 0.8, "Verdura"));
        productos.insertEnd("Pimiento"); datos.insertEnd(new ValoresNutricionales(27, 4.6, 1.2, 0.3, "Verdura"));
        productos.insertEnd("Porotos verdes"); datos.insertEnd(new ValoresNutricionales(47, 2.3, 1.8, 0.5, "Verdura"));
        productos.insertEnd("Puerros"); datos.insertEnd(new ValoresNutricionales(61, 14, 1.5, 0.3, "Verdura"));
        productos.insertEnd("Rábanos"); datos.insertEnd(new ValoresNutricionales(16, 1.9, 0.7, 0.1, "Verdura"));
        productos.insertEnd("Remolacha"); datos.insertEnd(new ValoresNutricionales(43, 9, 1.6, 0.2, "Verdura"));
        productos.insertEnd("Repollo"); datos.insertEnd(new ValoresNutricionales(31, 5.8, 1.4, 0.2, "Verdura"));
        productos.insertEnd("Rúcula"); datos.insertEnd(new ValoresNutricionales(25, 2, 2.6, 0.7, "Verdura"));
        productos.insertEnd("Brotes de Soja,"); datos.insertEnd(new ValoresNutricionales(122, 11, 13, 6, "Verdura"));
        productos.insertEnd("Tomate triturado en conserva"); datos.insertEnd(new ValoresNutricionales(32, 5, 1.6, 0.3, "Verdura"));
        productos.insertEnd("Tomates"); datos.insertEnd(new ValoresNutricionales(18, 2.6, 0.9, 0.2, "Verdura"));
        productos.insertEnd("Trufa"); datos.insertEnd(new ValoresNutricionales(30, 2.5, 3.2, 2.2, "Verdura"));
        productos.insertEnd("Zanahoria"); datos.insertEnd(new ValoresNutricionales(41, 5.2, 0.9, 0.2, "Verdura"));
        productos.insertEnd("Zumo de tomate"); datos.insertEnd(new ValoresNutricionales(18, 3.5, 1.2, 0.2, "Verdura"));
        productos.insertEnd("Arándanos"); datos.insertEnd(new ValoresNutricionales(57, 5.4, 0.7, 0.3, "Fruta"));
        productos.insertEnd("Caqui"); datos.insertEnd(new ValoresNutricionales(81, 14, 0.6, 0.4, "Fruta"));
        productos.insertEnd("Cereza"); datos.insertEnd(new ValoresNutricionales(50, 12, 1, 0.3, "Fruta"));
        productos.insertEnd("Chirimoya"); datos.insertEnd(new ValoresNutricionales(75, 23.5, 2, 0.7, "Fruta"));
        productos.insertEnd("Ciruela"); datos.insertEnd(new ValoresNutricionales(46, 9.9, 0.7, 0.3, "Fruta"));
        productos.insertEnd("Ciruela seca"); datos.insertEnd(new ValoresNutricionales(241, 63.9, 2.2, 0.7, "Fruta"));
        productos.insertEnd("Coco"); datos.insertEnd(new ValoresNutricionales(354, 3.3, 3.3, 33.5, "Fruta"));
        productos.insertEnd("Dátil"); datos.insertEnd(new ValoresNutricionales(282, 74.97, 2.45, 0.39, "Fruta"));
        productos.insertEnd("Dátil seco"); datos.insertEnd(new ValoresNutricionales(282, 74.97, 2.45, 0.39, "Fruta"));
        productos.insertEnd("Frambuesa"); datos.insertEnd(new ValoresNutricionales(52, 11.9, 1.2, 0.7, "Fruta"));
        productos.insertEnd("Fresas"); datos.insertEnd(new ValoresNutricionales(32, 4.9, 0.7, 0.4, "Fruta"));
        productos.insertEnd("Granada"); datos.insertEnd(new ValoresNutricionales(83, 18.7, 1.7, 1.7, "Fruta"));
        productos.insertEnd("Grosella"); datos.insertEnd(new ValoresNutricionales(37, 7.3, 1.6, 0.6, "Fruta"));
        productos.insertEnd("Higos"); datos.insertEnd(new ValoresNutricionales(80, 19.2, 1.2, 0.3, "Fruta"));
        productos.insertEnd("Higos secos"); datos.insertEnd(new ValoresNutricionales(249, 63.9, 2.5, 0.5, "Fruta"));
        productos.insertEnd("Kiwi"); datos.insertEnd(new ValoresNutricionales(61, 14.6, 1.1, 0.5, "Fruta"));
        productos.insertEnd("Limón"); datos.insertEnd(new ValoresNutricionales(29, 2.8, 0.6, 0.3, "Fruta"));
        productos.insertEnd("Mandarina"); datos.insertEnd(new ValoresNutricionales(53, 13.3, 0.8, 0.3, "Fruta"));
        productos.insertEnd("Mango"); datos.insertEnd(new ValoresNutricionales(60, 14.98, 0.82, 0.38, "Fruta"));
        productos.insertEnd("Manzana"); datos.insertEnd(new ValoresNutricionales(52, 11.3, 0.3, 0.2, "Fruta"));
        productos.insertEnd("Melón"); datos.insertEnd(new ValoresNutricionales(36, 8.2, 0.9, 0.2, "Fruta"));
        productos.insertEnd("Mora"); datos.insertEnd(new ValoresNutricionales(43, 4.4, 1.4, 0.5, "Fruta"));
        productos.insertEnd("Naranja"); datos.insertEnd(new ValoresNutricionales(43, 8.3, 1, 0.2, "Fruta"));
        productos.insertEnd("Nectarina"); datos.insertEnd(new ValoresNutricionales(44, 8.4, 1.1, 0.3, "Fruta"));
        productos.insertEnd("Nísperos"); datos.insertEnd(new ValoresNutricionales(44, 9.8, 0.91, 0.4, "Fruta"));
        productos.insertEnd("Papaya"); datos.insertEnd(new ValoresNutricionales(43, 10.8, 0.5, 0.2, "Fruta"));
        productos.insertEnd("Pera"); datos.insertEnd(new ValoresNutricionales(57, 15.23, 0.4, 0.2, "Fruta"));
        productos.insertEnd("Piña"); datos.insertEnd(new ValoresNutricionales(50, 13.1, 0.5, 0.1, "Fruta"));
        productos.insertEnd("Piña en almíbar"); datos.insertEnd(new ValoresNutricionales(50, 13.1, 0.5, 0.1, "Fruta"));
        productos.insertEnd("Plátano"); datos.insertEnd(new ValoresNutricionales(89, 12.2, 1.3, 0.3, "Fruta"));
        productos.insertEnd("Pomelo"); datos.insertEnd(new ValoresNutricionales(32, 8.2, 0.6, 0.2, "Fruta"));
        productos.insertEnd("Sandía"); datos.insertEnd(new ValoresNutricionales(30, 6.2, 0.6, 0.2, "Fruta"));
        productos.insertEnd("Uva"); datos.insertEnd(new ValoresNutricionales(69, 18.1, 0.6, 0.2, "Fruta"));
        productos.insertEnd("Uva pasa"); datos.insertEnd(new ValoresNutricionales(299, 79.2, 2.5, 0.5, "Fruta"));
        productos.insertEnd("Zumo de fruta"); datos.insertEnd(new ValoresNutricionales(45, 10.3, 0.5, 0.2, "Fruta"));
        productos.insertEnd("Zumo de Naranja"); datos.insertEnd(new ValoresNutricionales(43, 8.3, 0.7, 0.2, "Fruta"));

        productos.insertEnd("Almendras"); datos.insertEnd(new ValoresNutricionales(579,21.7,21.1,49.9,"Frutos secos"));
        productos.insertEnd("Avellanas"); datos.insertEnd(new ValoresNutricionales(628,6.1,15,60.8,"Frutos secos"));
        productos.insertEnd("Castañas"); datos.insertEnd(new ValoresNutricionales(196,40.2,2.3,1.3,"Frutos secos"));
        productos.insertEnd("Maní"); datos.insertEnd(new ValoresNutricionales(567,16.1,26.2,49.2,"Frutos secos"));
        productos.insertEnd("Nueces"); datos.insertEnd(new ValoresNutricionales(654,13.7,15.3,65.2,"Frutos secos"));
        productos.insertEnd("Piñones"); datos.insertEnd(new ValoresNutricionales(673,13.1,14,68.4,"Frutos secos"));
        productos.insertEnd("Pistacho"); datos.insertEnd(new ValoresNutricionales(557,27.3,21.2,45.3,"Frutos secos"));
        productos.insertEnd("Cuajada"); datos.insertEnd(new ValoresNutricionales(92,3.2,8.1,4.5,"Lacteo"));
        productos.insertEnd("Flan de huevo"); datos.insertEnd(new ValoresNutricionales(126,22.9,2.9,5,"Lacteo"));
        productos.insertEnd("Flan de vainilla"); datos.insertEnd(new ValoresNutricionales(102,19.8,2.4,2.6,"Lacteo"));
        productos.insertEnd("Helados lácteos"); datos.insertEnd(new ValoresNutricionales(177,18.3,3.7,8.4,"Lacteo"));
        productos.insertEnd("Leche condensada c/azúcar"); datos.insertEnd(new ValoresNutricionales(321,8.5,8.3,8.2,"Lacteo"));
        productos.insertEnd("Leche condensada s/azúcar"); datos.insertEnd(new ValoresNutricionales(160,54.8,29.6,3.2,"Lacteo"));
        productos.insertEnd("Leche de cabra"); datos.insertEnd(new ValoresNutricionales(61,3.6,4.4,3.8,"Lacteo"));
        productos.insertEnd("Leche de oveja"); datos.insertEnd(new ValoresNutricionales(95,4.7,6,6.3,"Lacteo"));
        productos.insertEnd("Leche descremada"); datos.insertEnd(new ValoresNutricionales(36,4.8,3.4,0.2,"Lacteo"));
        productos.insertEnd("Leche en polvo descremada"); datos.insertEnd(new ValoresNutricionales(358,52.2,35.1,1.3,"Lacteo"));
        productos.insertEnd("Leche en polvo entera"); datos.insertEnd(new ValoresNutricionales(496,38.5,25.5,26.3,"Lacteo"));
        productos.insertEnd("Leche entera"); datos.insertEnd(new ValoresNutricionales(61,4.7,3.2,3.6,"Lacteo"));
        productos.insertEnd("Leche semi descremada"); datos.insertEnd(new ValoresNutricionales(50,5.1,8.8,0.3,"Lacteo"));
        productos.insertEnd("Mousse"); datos.insertEnd(new ValoresNutricionales(177,13.3,1.6,14.5,"Lacteo"));
        productos.insertEnd("Nata o crema de leche"); datos.insertEnd(new ValoresNutricionales(288,2.8,2.9,30.4,"Lacteo"));
        productos.insertEnd("Queso blanco desnatado"); datos.insertEnd(new ValoresNutricionales(70,2.6,8.5,3.4,"Lacteo"));
        productos.insertEnd("Queso Brie"); datos.insertEnd(new ValoresNutricionales(334,0.5,24.9,28.7,"Lacteo"));
        productos.insertEnd("Queso camembert"); datos.insertEnd(new ValoresNutricionales(300,0.5,19.8,24.3,"Lacteo"));
        productos.insertEnd("Queso cheddar"); datos.insertEnd(new ValoresNutricionales(406,1.3,23.4,33.1,"Lacteo"));
        productos.insertEnd("Queso crema"); datos.insertEnd(new ValoresNutricionales(296,5.6,5.5,30.5,"Lacteo"));
        productos.insertEnd("Queso de bola"); datos.insertEnd(new ValoresNutricionales(356,3.6,20.3,29.2,"Lacteo"));
        productos.insertEnd("Queso de Burgos"); datos.insertEnd(new ValoresNutricionales(173,0.8,11.9,14.3,"Lacteo"));
        productos.insertEnd("Queso de oveja"); datos.insertEnd(new ValoresNutricionales(274,2.5,23,22.2,"Lacteo"));
        productos.insertEnd("Queso edam"); datos.insertEnd(new ValoresNutricionales(357,1.4,27.4,28.4,"Lacteo"));
        productos.insertEnd("Queso emmental"); datos.insertEnd(new ValoresNutricionales(393,0.5,29,32.3,"Lacteo"));
        productos.insertEnd("Queso fundido untable"); datos.insertEnd(new ValoresNutricionales(272,4.9,10.3,24.9,"Lacteo"));
        productos.insertEnd("Queso gruyere"); datos.insertEnd(new ValoresNutricionales(413,0.4,32.6,32.4,"Lacteo"));
        productos.insertEnd("Queso manchego"); datos.insertEnd(new ValoresNutricionales(372,0.7,28.7,29.7,"Lacteo"));
        productos.insertEnd("Queso mozzarella"); datos.insertEnd(new ValoresNutricionales(300,1.9,21.3,22.2,"Lacteo"));
        productos.insertEnd("Queso parmesano"); datos.insertEnd(new ValoresNutricionales(431,0.9,28.4,34.9,"Lacteo"));
        productos.insertEnd("Queso ricota"); datos.insertEnd(new ValoresNutricionales(174,1,11,14,"Lacteo"));
        productos.insertEnd("Queso roquefort"); datos.insertEnd(new ValoresNutricionales(369,0.5,21.5,30.6,"Lacteo"));
        productos.insertEnd("Requesón"); datos.insertEnd(new ValoresNutricionales(120,1.4,11.1,8.6,"Lacteo"));
        productos.insertEnd("Yogur desnatado"); datos.insertEnd(new ValoresNutricionales(50,4.9,3.6,0.1,"Lacteo"));
        productos.insertEnd("Yogur desnatado con frutas"); datos.insertEnd(new ValoresNutricionales(86,14.1,2.8,0.4,"Lacteo"));
        productos.insertEnd("Yogur enriquecido con nata"); datos.insertEnd(new ValoresNutricionales(82,8.8,5.2,4.7,"Lacteo"));
        productos.insertEnd("Yogur natural"); datos.insertEnd(new ValoresNutricionales(61,4,4,3.3,"Lacteo"));
        productos.insertEnd("Yogur natural con fruta"); datos.insertEnd(new ValoresNutricionales(100,14.3,2.6,2.6,"Lacteo"));

        productos.insertEnd("Bacon"); datos.insertEnd(new ValoresNutricionales(665,21.2,46,59.4,"Carne"));
        productos.insertEnd("Butifarra cocida"); datos.insertEnd(new ValoresNutricionales(390,9.2,32,2.6,"Carne"));
        productos.insertEnd("Butifarra, salchicha fresca"); datos.insertEnd(new ValoresNutricionales(326,10.8,190,0.4,"Carne"));
        productos.insertEnd("Cabrito"); datos.insertEnd(new ValoresNutricionales(127,21.7,383,0.2,"Carne"));
        productos.insertEnd("chuleta de Cerdo"); datos.insertEnd(new ValoresNutricionales(330,18.7,344,25.6,"Carne"));
        productos.insertEnd("hígado de Cerdo"); datos.insertEnd(new ValoresNutricionales(153,3.6,49,1.45,"Carne"));
        productos.insertEnd("lomo de Cerdo"); datos.insertEnd(new ValoresNutricionales(208,9.4,117,34.3,"Carne"));
        productos.insertEnd("Chicharrón"); datos.insertEnd(new ValoresNutricionales(601,0,473,31.3,"Carne"));
        productos.insertEnd("Chorizo"); datos.insertEnd(new ValoresNutricionales(468,2.5,97,17.4,"Carne"));
        productos.insertEnd("Ciervo"); datos.insertEnd(new ValoresNutricionales(120,21.5,242,4.15,"Carne"));
        productos.insertEnd("Codorniz y perdiz"); datos.insertEnd(new ValoresNutricionales(114,17.5,250,25.9,"Carne"));
        productos.insertEnd("Conejo"); datos.insertEnd(new ValoresNutricionales(162,1,234,26.7,"Carne"));
        productos.insertEnd("Cordero lechón"); datos.insertEnd(new ValoresNutricionales(105,31.6,482,1.28,"Carne"));
        productos.insertEnd("Cordero pierna"); datos.insertEnd(new ValoresNutricionales(98,12.2,166,0.1,"Carne"));
        productos.insertEnd("costillas de Cordero"); datos.insertEnd(new ValoresNutricionales(215,46.9,157,7,"Carne"));
        productos.insertEnd("hígado de Cordero"); datos.insertEnd(new ValoresNutricionales(132,3.69,467,4.51,"Carne"));
        productos.insertEnd("Faisán"); datos.insertEnd(new ValoresNutricionales(144,37.9,247,3.5,"Carne"));
        productos.insertEnd("Foie-Gras"); datos.insertEnd(new ValoresNutricionales(518,468,14,31.6,"Carne"));
        productos.insertEnd("Gallina"); datos.insertEnd(new ValoresNutricionales(369,8.7,394,3.03,"Carne"));
        productos.insertEnd("Hamburguesa"); datos.insertEnd(new ValoresNutricionales(230,14.7,297,5.6,"Carne"));
        productos.insertEnd("Jabalí"); datos.insertEnd(new ValoresNutricionales(107,37.3,395,4.6,"Carne"));
        productos.insertEnd("Jamón"); datos.insertEnd(new ValoresNutricionales(380,48.8,456,30.3,"Carne"));
        productos.insertEnd("Jamón cocido"); datos.insertEnd(new ValoresNutricionales(126,41.9,61,18.4,"Carne"));
        productos.insertEnd("Jamón crudo"); datos.insertEnd(new ValoresNutricionales(296,4.7,459,22,"Carne"));
        productos.insertEnd("Jamón York"); datos.insertEnd(new ValoresNutricionales(289,2.3,392,7.7,"Carne"));
        productos.insertEnd("Lengua de vaca"); datos.insertEnd(new ValoresNutricionales(191,8.3,3,27.9,"Carne"));
        productos.insertEnd("Lomo embuchado"); datos.insertEnd(new ValoresNutricionales(380,42.1,407,7,"Carne"));
        productos.insertEnd("Mortadela"); datos.insertEnd(new ValoresNutricionales(265,31.1,39,46.2,"Carne"));
        productos.insertEnd("Pato"); datos.insertEnd(new ValoresNutricionales(200,44.8,1,40.8,"Carne"));
        productos.insertEnd("Muslo de Pavo"); datos.insertEnd(new ValoresNutricionales(186,1.9,198,1.2,"Carne"));
        productos.insertEnd("Pechuga de Pavo"); datos.insertEnd(new ValoresNutricionales(134,30.2,431,39.1,"Carne"));
        productos.insertEnd("Perdiz"); datos.insertEnd(new ValoresNutricionales(120,7.4,65,11,"Carne"));
        productos.insertEnd("Pies de cerdo"); datos.insertEnd(new ValoresNutricionales(290,25.6,498,6.6,"Carne"));
        productos.insertEnd("Pollo, Hígado"); datos.insertEnd(new ValoresNutricionales(129,8,420,2.3,"Carne"));
        productos.insertEnd("Pollo, Muslo"); datos.insertEnd(new ValoresNutricionales(186,42.8,145,36.4,"Carne"));
        productos.insertEnd("Pollo"); datos.insertEnd(new ValoresNutricionales(134,28.9,32,37.3,"Carne"));
        productos.insertEnd("Salami"); datos.insertEnd(new ValoresNutricionales(325,12,478,44.8,"Carne"));
        productos.insertEnd("Salchicha Frankfurt"); datos.insertEnd(new ValoresNutricionales(315,29.5,42,11.3,"Carne"));
        productos.insertEnd("Salchichón"); datos.insertEnd(new ValoresNutricionales(294,6.6,342,0.7,"Carne"));
        productos.insertEnd("Ternera"); datos.insertEnd(new ValoresNutricionales(181,5.4,213,48.9,"Carne"));
        productos.insertEnd("chuleta de Ternera"); datos.insertEnd(new ValoresNutricionales(168,29.5,239,41,"Carne"));
        productos.insertEnd("Ternera, hígado"); datos.insertEnd(new ValoresNutricionales(140,14.3,398,12.6,"Carne"));
        productos.insertEnd("lengua de Ternera"); datos.insertEnd(new ValoresNutricionales(207,45.8,423,31.5,"Carne"));
        productos.insertEnd("riñón de Ternera"); datos.insertEnd(new ValoresNutricionales(86,27,74,16.2,"Carne"));
        productos.insertEnd("sesos de Ternera"); datos.insertEnd(new ValoresNutricionales(125,23.9,452,2.5,"Carne"));
        productos.insertEnd("solomillo de ternera"); datos.insertEnd(new ValoresNutricionales(290,24.5,499,9.5,"Carne"));
        productos.insertEnd("Tira de asado"); datos.insertEnd(new ValoresNutricionales(401,40.9,272,33.2,"Carne"));
        productos.insertEnd("Tripas"); datos.insertEnd(new ValoresNutricionales(100,12.9,490,4.1,"Carne"));
        productos.insertEnd("Vacuno, Hígado"); datos.insertEnd(new ValoresNutricionales(129,15,220,23.5,"Carne"));

        productos.insertEnd("Almejas"); datos.insertEnd(new ValoresNutricionales(50,2.14,459,38.6,"Pescado"));
        productos.insertEnd("Anchoas"); datos.insertEnd(new ValoresNutricionales(175,15.2,331,43.9,"Pescado"));
        productos.insertEnd("Anguilas"); datos.insertEnd(new ValoresNutricionales(200,17.2,274,9.5,"Pescado"));
        productos.insertEnd("Atún en lata con aceite vegetal"); datos.insertEnd(new ValoresNutricionales(280,45.1,125,32.3,"Pescado"));
        productos.insertEnd("Atún en lata con agua"); datos.insertEnd(new ValoresNutricionales(127,34.2,76,34.7,"Pescado"));
        productos.insertEnd("Atún fresco"); datos.insertEnd(new ValoresNutricionales(225,38.4,155,24.8,"Pescado"));
        productos.insertEnd("Bacalao fresco"); datos.insertEnd(new ValoresNutricionales(74,10.4,258,33.4,"Pescado"));
        productos.insertEnd("Bacalao seco"); datos.insertEnd(new ValoresNutricionales(322,12.9,174,28.4,"Pescado"));
        productos.insertEnd("Besugo"); datos.insertEnd(new ValoresNutricionales(118,23.7,37,31.3,"Pescado"));
        productos.insertEnd("Caballa"); datos.insertEnd(new ValoresNutricionales(153,32.7,446,21.3,"Pescado"));
        productos.insertEnd("Calamar"); datos.insertEnd(new ValoresNutricionales(82,25.3,11,36.2,"Pescado"));
        productos.insertEnd("Cangrejo"); datos.insertEnd(new ValoresNutricionales(85,24.4,119,31.9,"Pescado"));
        productos.insertEnd("Caviar"); datos.insertEnd(new ValoresNutricionales(233,29.4,54,29.7,"Pescado"));
        productos.insertEnd("Congrio"); datos.insertEnd(new ValoresNutricionales(112,27.8,403,17,"Pescado"));
        productos.insertEnd("Dorada"); datos.insertEnd(new ValoresNutricionales(80,8.2,404,8.2,"Pescado"));
        productos.insertEnd("Gallo"); datos.insertEnd(new ValoresNutricionales(73,6.9,231,24.1,"Pescado"));
        productos.insertEnd("Gambas"); datos.insertEnd(new ValoresNutricionales(96,49.1,380,40.9,"Pescado"));
        productos.insertEnd("Langosta"); datos.insertEnd(new ValoresNutricionales(67,15.2,231,7.6,"Pescado"));
        productos.insertEnd("Langostino"); datos.insertEnd(new ValoresNutricionales(96,16.8,259,47.8,"Pescado"));
        productos.insertEnd("Lenguado"); datos.insertEnd(new ValoresNutricionales(73,18.1,189,11.8,"Pescado"));
        productos.insertEnd("Lubina"); datos.insertEnd(new ValoresNutricionales(118,41.1,43,1.8,"Pescado"));
        productos.insertEnd("Lucio"); datos.insertEnd(new ValoresNutricionales(81,2.1,340,21.7,"Pescado"));
        productos.insertEnd("Mejillón"); datos.insertEnd(new ValoresNutricionales(74,13.9,360,2.2,"Pescado"));
        productos.insertEnd("Merluza"); datos.insertEnd(new ValoresNutricionales(86,39.2,158,1.6,"Pescado"));
        productos.insertEnd("Mero"); datos.insertEnd(new ValoresNutricionales(118,16.8,148,7.1,"Pescado"));
        productos.insertEnd("Ostras"); datos.insertEnd(new ValoresNutricionales(80,3,58,12.9,"Pescado"));
        productos.insertEnd("Pejerrey"); datos.insertEnd(new ValoresNutricionales(87,14,465,2.1,"Pescado"));
        productos.insertEnd("Pez espada"); datos.insertEnd(new ValoresNutricionales(109,30.5,170,0.5,"Pescado"));
        productos.insertEnd("Pulpo"); datos.insertEnd(new ValoresNutricionales(57,21,95,22.7,"Pescado"));
        productos.insertEnd("Rodaballo"); datos.insertEnd(new ValoresNutricionales(81,30.8,248,0.3,"Pescado"));
        productos.insertEnd("Salmón"); datos.insertEnd(new ValoresNutricionales(172,39.2,345,1.6,"Pescado"));
        productos.insertEnd("Salmón ahumado"); datos.insertEnd(new ValoresNutricionales(154,25,136,20.8,"Pescado"));
        productos.insertEnd("Salmonete"); datos.insertEnd(new ValoresNutricionales(97,15.6,38,8.7,"Pescado"));
        productos.insertEnd("Sardina en lata con aceite vegetal"); datos.insertEnd(new ValoresNutricionales(192,2.2,372,3.5,"Pescado"));
        productos.insertEnd("Sardinas"); datos.insertEnd(new ValoresNutricionales(151,2.6,455,7.6,"Pescado"));
        productos.insertEnd("Trucha"); datos.insertEnd(new ValoresNutricionales(94,24.1,449,11.8,"Pescado"));

        productos.insertEnd("Azúcar");datos.insertEnd(new ValoresNutricionales(380,33.7,399,31.2,"Dulce"));
        productos.insertEnd("Cacao en polvo con azúcar instantáneo");datos.insertEnd(new ValoresNutricionales(366,43.6,34,90,"Dulce"));
        productos.insertEnd("Caramelos");datos.insertEnd(new ValoresNutricionales(378,35.9,299,71,"Dulce"));
        productos.insertEnd("Chocolate con leche");datos.insertEnd(new ValoresNutricionales(550,135,26,177,"Dulce"));
        productos.insertEnd("Chocolate sin leche");datos.insertEnd(new ValoresNutricionales(530,33,72,25,"Dulce"));
        productos.insertEnd("Crema chocolate con avellanas");datos.insertEnd(new ValoresNutricionales(549,21.1,243,293,"Dulce"));
        productos.insertEnd("Dulce de membrillo");datos.insertEnd(new ValoresNutricionales(215,36.4,280,97,"Dulce"));
        productos.insertEnd("Helados de agua");datos.insertEnd(new ValoresNutricionales(139,30,20,242,"Dulce"));
        productos.insertEnd("Mermeladas con azúcar");datos.insertEnd(new ValoresNutricionales(280,14,451,442,"Dulce"));
        productos.insertEnd("Mermeladas sin azúcar");datos.insertEnd(new ValoresNutricionales(145,12.7,250,47,"Dulce"));
        productos.insertEnd("Miel");datos.insertEnd(new ValoresNutricionales(300,24.7,380,413,"Dulce"));
        productos.insertEnd("Arroz blanco");datos.insertEnd(new ValoresNutricionales(354,64,429,327,"Cereal"));
        productos.insertEnd("Arroz integral");datos.insertEnd(new ValoresNutricionales(350,1,328,9,"Cereal"));
        productos.insertEnd("Avena");datos.insertEnd(new ValoresNutricionales(367,20,344,46,"Cereal"));
        productos.insertEnd("Cebada");datos.insertEnd(new ValoresNutricionales(373,40,201,223,"Cereal"));
        productos.insertEnd("Centeno");datos.insertEnd(new ValoresNutricionales(350,4,337,269,"Cereal"));
        productos.insertEnd("Cereales con chocolate");datos.insertEnd(new ValoresNutricionales(358,37.7,227,425,"Cereal"));
        productos.insertEnd("Cereales desayuno, con miel");datos.insertEnd(new ValoresNutricionales(386,64,255,368,"Cereal"));
        productos.insertEnd("Copos de maíz");datos.insertEnd(new ValoresNutricionales(350,66,90,270,"Cereal"));
        productos.insertEnd("Harina de maíz");datos.insertEnd(new ValoresNutricionales(349,175,297,445,"Cereal"));
        productos.insertEnd("Harina de trigo integral");datos.insertEnd(new ValoresNutricionales(340,95,361,346,"Cereal"));
        productos.insertEnd("Harina de trigo refinada");datos.insertEnd(new ValoresNutricionales(353,412,474,469,"Cereal"));
        productos.insertEnd("Pan de centeno");datos.insertEnd(new ValoresNutricionales(241,31,197,209,"Cereal"));
        productos.insertEnd("Pan de trigo blanco");datos.insertEnd(new ValoresNutricionales(255,71,406,255,"Cereal"));
        productos.insertEnd("Pan de trigo integral");datos.insertEnd(new ValoresNutricionales(239,215,273,489,"Cereal"));
        productos.insertEnd("Pan de trigo molde blanco");datos.insertEnd(new ValoresNutricionales(233,246,130,228,"Cereal"));
        productos.insertEnd("Pan de trigo molde integral");datos.insertEnd(new ValoresNutricionales(216,228,61,492,"Cereal"));
        productos.insertEnd("Pasta al huevo");datos.insertEnd(new ValoresNutricionales(368,36.7,399,163,"Cereal"));
        productos.insertEnd("Pasta de sémola");datos.insertEnd(new ValoresNutricionales(361,187,260,332,"Cereal"));
        productos.insertEnd("Polenta");datos.insertEnd(new ValoresNutricionales(358,399,333,403,"Cereal"));
        productos.insertEnd("Sémola de trigo");datos.insertEnd(new ValoresNutricionales(368,291,477,260,"Cereal"));
        productos.insertEnd("Yuca");datos.insertEnd(new ValoresNutricionales(338,5,222,171,"Cereal"));
        productos.insertEnd("Garbanzos");datos.insertEnd(new ValoresNutricionales(361,48.3,65,457,"Legumbre"));
        productos.insertEnd("Judías");datos.insertEnd(new ValoresNutricionales(343,187,417,454,"Legumbre"));
        productos.insertEnd("Lentejas");datos.insertEnd(new ValoresNutricionales(336,179,419,444,"Legumbre"));
        productos.insertEnd("Clara");datos.insertEnd(new ValoresNutricionales(48,21.5,134,44.1,"Huevo"));
        productos.insertEnd("Huevo duro");datos.insertEnd(new ValoresNutricionales(147,39.9,233,144,"Huevo"));
        productos.insertEnd("Huevo entero");datos.insertEnd(new ValoresNutricionales(162,20.7,187,95,"Huevo"));
        productos.insertEnd("Yema");datos.insertEnd(new ValoresNutricionales(368,14,116,466,"Huevo"));
        productos.insertEnd("Bizcocho");datos.insertEnd(new ValoresNutricionales(456,152,322,426,"Dulce"));
        productos.insertEnd("Croissant chocolate");datos.insertEnd(new ValoresNutricionales(469,27,127,303,"Dulce"));
        productos.insertEnd("Croissant, donut");datos.insertEnd(new ValoresNutricionales(456,1,166,0,"Dulce"));
        productos.insertEnd("Galletas de chocolate");datos.insertEnd(new ValoresNutricionales(524,374,377,408,"Dulce"));
        productos.insertEnd("Galletas de mantequilla tipo “Danesas”");datos.insertEnd(new ValoresNutricionales(397,486,241,94,"Dulce"));
        productos.insertEnd("Galletas saladas");datos.insertEnd(new ValoresNutricionales(464,268,448,162,"Dulce"));
        productos.insertEnd("Magdalenas");datos.insertEnd(new ValoresNutricionales(469,220,382,364,"Dulce"));
        productos.insertEnd("Pasta de hojaldre cocida");datos.insertEnd(new ValoresNutricionales(565,157,157,260,"Cereal"));
        productos.insertEnd("Pastel de manzana");datos.insertEnd(new ValoresNutricionales(311,452,59,151,"Dulce"));
        productos.insertEnd("Pastel de manzana, masa hojaldre");datos.insertEnd(new ValoresNutricionales(456,450,228,282,"Dulce"));
        productos.insertEnd("Pastel de queso");datos.insertEnd(new ValoresNutricionales(414,115,291,336,"Dulce"));
        productos.insertEnd("Agua ardiente");datos.insertEnd(new ValoresNutricionales(280,309,303,421,"Bebida"));

        productos.insertEnd("Agua tónica");datos.insertEnd(new ValoresNutricionales(34,180,317,127,"Bebida"));
        productos.insertEnd("Anís");datos.insertEnd(new ValoresNutricionales(312,287,417,210,"Bebida"));
        productos.insertEnd("Batido lácteo de cacao");datos.insertEnd(new ValoresNutricionales(100,222,383,27,"Bebida"));
        productos.insertEnd("Cacao en polvo sin azúcar a la taza");datos.insertEnd(new ValoresNutricionales(439,421,67,145,"Bebida"));
        productos.insertEnd("Café");datos.insertEnd(new ValoresNutricionales(1,113,123,109,"Bebida"));
        productos.insertEnd("Cerveza negra");datos.insertEnd(new ValoresNutricionales(37,397,228,177,"Bebida"));
        productos.insertEnd("Cerveza rubia");datos.insertEnd(new ValoresNutricionales(45,466,287,159,"Bebida"));
        productos.insertEnd("Champaña demi-sec");datos.insertEnd(new ValoresNutricionales(90,267,29,450,"Bebida"));
        productos.insertEnd("Champaña dulce");datos.insertEnd(new ValoresNutricionales(118,303,26,304,"Bebida"));
        productos.insertEnd("Champaña seca");datos.insertEnd(new ValoresNutricionales(85,288,467,199,"Bebida"));
        productos.insertEnd("Coñac, brandy");datos.insertEnd(new ValoresNutricionales(243,435,63,50,"Bebida"));
        productos.insertEnd("Crema de cacao");datos.insertEnd(new ValoresNutricionales(260,388,368,449,"Bebida"));
        productos.insertEnd("Daiquiri");datos.insertEnd(new ValoresNutricionales(122,428,480,299,"Bebida"));
        productos.insertEnd("Gin & Tónica");datos.insertEnd(new ValoresNutricionales(76,36,84,20,"Bebida"));
        productos.insertEnd("Ginebra");datos.insertEnd(new ValoresNutricionales(244,444,25,455,"Bebida"));
        productos.insertEnd("Leche de almendras");datos.insertEnd(new ValoresNutricionales(335,347,259,480,"Bebida"));
        productos.insertEnd("Licor de caña");datos.insertEnd(new ValoresNutricionales(273,428,371,418,"Bebida"));
        productos.insertEnd("Piña colada");datos.insertEnd(new ValoresNutricionales(194,392,318,188,"Bebida"));
        productos.insertEnd("Pisco");datos.insertEnd(new ValoresNutricionales(210,11,40,450,"Bebida"));
        productos.insertEnd("Refrescos carbonatados");datos.insertEnd(new ValoresNutricionales(48,325,372,118,"Bebida"));
        productos.insertEnd("Ron");datos.insertEnd(new ValoresNutricionales(244,120,406,395,"Bebida"));
        productos.insertEnd("Sidra dulce");datos.insertEnd(new ValoresNutricionales(33,390,370,97,"Bebida"));
        productos.insertEnd("Sidra seca");datos.insertEnd(new ValoresNutricionales(35,260,191,432,"Bebida"));
        productos.insertEnd("Té");datos.insertEnd(new ValoresNutricionales(1,191,475,40,"Bebida"));
        productos.insertEnd("Vermouth amargo");datos.insertEnd(new ValoresNutricionales(112,350,442,203,"Bebida"));
        productos.insertEnd("Vermouth dulce");datos.insertEnd(new ValoresNutricionales(160,297,45,437,"Bebida"));
        productos.insertEnd("Vino de mesa");datos.insertEnd(new ValoresNutricionales(70,132,269,202,"Bebida"));
        productos.insertEnd("Vino dulce, jerez");datos.insertEnd(new ValoresNutricionales(160,121,401,24,"Bebida"));
        productos.insertEnd("Vino oporto");datos.insertEnd(new ValoresNutricionales(160,66,274,209,"Bebida"));
        productos.insertEnd("Vodka");datos.insertEnd(new ValoresNutricionales(315,191,96,423,"Bebida"));
        productos.insertEnd("Whisky");datos.insertEnd(new ValoresNutricionales(244,299,4,170,"Bebida"));
        productos.insertEnd("Aceite de girasol");datos.insertEnd(new ValoresNutricionales(900,207,401,439,"Otros"));
        productos.insertEnd("Aceite de oliva");datos.insertEnd(new ValoresNutricionales(900,471,417,56,"Otros"));
        productos.insertEnd("Manteca");datos.insertEnd(new ValoresNutricionales(670,224,201,439,"Otros"));
        productos.insertEnd("Mantequilla");datos.insertEnd(new ValoresNutricionales(752,7,143,259,"Otros"));
        productos.insertEnd("Margarina vegetal");datos.insertEnd(new ValoresNutricionales(752,410,458,153,"Otros"));
        productos.insertEnd("Bechamel");datos.insertEnd(new ValoresNutricionales(115,227,118,465,"Otros"));
        productos.insertEnd("Caldos concentrados");datos.insertEnd(new ValoresNutricionales(259,454,499,289,"Otros"));
        productos.insertEnd("Ketchup");datos.insertEnd(new ValoresNutricionales(98,198,171,117,"Otros"));
        productos.insertEnd("Mayonesa");datos.insertEnd(new ValoresNutricionales(718,210,146,185,"Otros"));
        productos.insertEnd("Mayonesa light");datos.insertEnd(new ValoresNutricionales(374,279,484,435,"Otros"));
        productos.insertEnd("Mostaza");datos.insertEnd(new ValoresNutricionales(15,104,465,459,"Otros"));
        productos.insertEnd("Salsa de soja");datos.insertEnd(new ValoresNutricionales(61,309,291,468,"Otros"));
        productos.insertEnd("Salsa de tomate en conserva");datos.insertEnd(new ValoresNutricionales(86,117,43,154,"Otros"));
        productos.insertEnd("Sofrito");datos.insertEnd(new ValoresNutricionales(116,337,329,382,"Otros"));
        productos.insertEnd("Vinagres");datos.insertEnd(new ValoresNutricionales(8,0,310,426,"Otros"));


        int pos=productos.indexOf(nombre);
        if (pos>=0 ){
            return datos.getValorPorPosicion(pos);
        }return null;
    }


}
